//===--- IndexAction.cpp -----------------------------------------*- C++-*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "IndexAction.h"
#include "AST.h"
#include "Headers.h"
#include "SourceCode.h"
#include "clang-include-cleaner/Record.h"
#include "index/Relation.h"
#include "index/Serialization.h"
#include "index/SymbolCollector.h"
#include "index/SymbolOrigin.h"
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/FrontendAction.h"
#include "clang/Index/IndexingAction.h"
#include "clang/Index/IndexingOptions.h"
#include "clang/Lex/HeaderSearch.h"
#include "clang/Lex/ModuleMap.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/Path.h"
#include <functional>
#include <memory>
#include <optional>
#include <utility>

namespace clang {
namespace clangd {
namespace {

std::optional<std::string> toURI(OptionalFileEntryRef File) {
  if (!File)
    return std::nullopt;
  auto AbsolutePath = File->getFileEntry().tryGetRealPathName();
  llvm::SmallString<256> Normalized;
  if (AbsolutePath.empty()) {
    if (!llvm::sys::path::is_absolute(File->getName()))
      return std::nullopt;
    Normalized = File->getName();
    llvm::sys::path::remove_dots(Normalized, /*remove_dot_dot=*/true);
    AbsolutePath = Normalized;
  }
  return URI::create(AbsolutePath).toString();
}

std::optional<FileDigest> digestFileEntry(const SourceManager &SM,
                                          FileEntryRef File, FileID FID) {
  if (FID.isValid())
    if (auto Digest = digestFile(SM, FID))
      return Digest;
  auto Buffer = SM.getFileManager().getBufferForFile(File);
  if (!Buffer)
    return std::nullopt;
  return digest((*Buffer)->getBuffer());
}

std::optional<llvm::StringRef> recordFileNode(const SourceManager &SM,
                                              IncludeGraph &IG,
                                              FileEntryRef File,
                                              FileID FID = FileID()) {
  auto URI = toURI(File);
  if (!URI)
    return std::nullopt;
  auto I = IG.try_emplace(*URI).first;
  IncludeGraphNode &Node = I->getValue();
  if (Node.URI.data() != I->getKeyData())
    Node.URI = I->getKey();
  const FileDigest EmptyDigest{{0}};
  if (Node.Digest == EmptyDigest)
    if (auto Digest = digestFileEntry(SM, File, FID))
      Node.Digest = *Digest;
  return I->getKey();
}

// Collects the nodes and edges of include graph during indexing action.
// Important: The graph generated by those callbacks might contain cycles and
// self edges.
struct IncludeGraphCollector : public PPCallbacks {
public:
  IncludeGraphCollector(const SourceManager &SM, IncludeGraph &IG)
      : SM(SM), IG(IG) {}

  // Marks entered files and identifies the translation unit.
  void FileChanged(SourceLocation Loc, FileChangeReason Reason,
                   SrcMgr::CharacteristicKind FileType,
                   FileID PrevFID) override {
    // We only need to process each file once. So we don't care about anything
    // but entries.
    if (Reason != FileChangeReason::EnterFile)
      return;

    const auto FileID = SM.getFileID(Loc);
    auto File = SM.getFileEntryRefForID(FileID);
    if (!File)
      return;
    auto URI = recordFileNode(SM, IG, *File, FileID);
    if (!URI)
      return;
    IncludeGraphNode &Node = IG.find(*URI)->getValue();
#ifndef NDEBUG
    auto Digest = digestFile(SM, FileID);
    assert(Digest && Node.Digest == *Digest && "Same file, different digest?");
#endif
    if (FileID == SM.getMainFileID())
      Node.Flags |= IncludeGraphNode::SourceFlag::IsTU;
  }

  // Add edges from including files to includes.
  void InclusionDirective(SourceLocation HashLoc, const Token &IncludeTok,
                          llvm::StringRef FileName, bool IsAngled,
                          CharSourceRange FilenameRange,
                          OptionalFileEntryRef File, llvm::StringRef SearchPath,
                          llvm::StringRef RelativePath,
                          const Module *SuggestedModule, bool ModuleImported,
                          SrcMgr::CharacteristicKind FileType) override {
    if (!File)
      return;
    auto IncludeURI = recordFileNode(SM, IG, *File);
    if (!IncludeURI)
      return;

    auto IncludingURI = toURI(SM.getFileEntryRefForID(SM.getFileID(HashLoc)));
    if (!IncludingURI) {
      auto NodeForInclude = IG.try_emplace(*IncludeURI).first;
      NodeForInclude->getValue().Flags |=
          IncludeGraphNode::SourceFlag::IsCommandInput;
      return;
    }

    auto NodeForInclude = *IncludeURI;
    auto NodeForIncluding = IG.try_emplace(*IncludingURI);

    NodeForIncluding.first->getValue().DirectIncludes.push_back(NodeForInclude);
  }

  // Sanity check to ensure we have already populated a skipped file.
  void FileSkipped(const FileEntryRef &SkippedFile, const Token &FilenameTok,
                   SrcMgr::CharacteristicKind FileType) override {
#ifndef NDEBUG
    auto URI = toURI(SkippedFile);
    if (!URI)
      return;
    auto I = IG.try_emplace(*URI);
    assert(!I.second && "File inserted for the first time on skip.");
    assert(I.first->getKeyData() == I.first->getValue().URI.data() &&
           "Node have not been populated yet");
#endif
  }

  void HasInclude(SourceLocation Loc, StringRef FileName, bool IsAngled,
                  OptionalFileEntryRef File,
                  SrcMgr::CharacteristicKind FileType) override {
    auto URI =
        toURI(SM.getFileEntryRefForID(SM.getFileID(SM.getExpansionLoc(Loc))));
    if (!URI)
      return;
    auto Node = IG.find(*URI);
    if (Node != IG.end())
      Node->getValue().Flags |= IncludeGraphNode::SourceFlag::HasFileQuery;
  }

private:
  const SourceManager &SM;
  IncludeGraph &IG;
};

struct ModuleMapCollector : public ModuleMapCallbacks {
  ModuleMapCollector(const SourceManager &SM, IncludeGraph &IG)
      : SM(SM), IG(IG) {}

  void moduleMapFileRead(SourceLocation FileStart, FileEntryRef File,
                         bool IsSystem) override {
    FileID FID =
        FileStart.isValid() ? SM.getFileID(FileStart) : SM.translateFile(File);
    auto URI = recordFileNode(SM, IG, File, FID);
    if (!URI)
      return;
    IncludeGraphNode &Node = IG.find(*URI)->getValue();
    Node.Flags |= IncludeGraphNode::SourceFlag::IsModuleMap;
  }

private:
  const SourceManager &SM;
  IncludeGraph &IG;
};

// Wraps the index action and reports index data after each translation unit.
class IndexAction : public ASTFrontendAction {
public:
  IndexAction(std::shared_ptr<SymbolCollector> C,
              std::unique_ptr<include_cleaner::PragmaIncludes> PI,
              const index::IndexingOptions &Opts,
              std::function<void(IndexFileIn)> IndexContentsCallback)
      : IndexContentsCallback(IndexContentsCallback), Collector(C),
        PI(std::move(PI)), Opts(Opts) {
    this->Opts.ShouldTraverseDecl = [this](const Decl *D) {
      // Many operations performed during indexing is linear in terms of depth
      // of the decl (USR generation, name lookups, figuring out role of a
      // reference are some examples). Since we index all the decls nested
      // inside, it becomes quadratic. So we give up on nested symbols.
      if (isDeeplyNested(D))
        return false;
      // If D is a likely forwarding function we need the body to index indirect
      // constructor calls (e.g. `make_unique`)
      if (auto *FT = llvm::dyn_cast<clang::FunctionTemplateDecl>(D);
          FT && isLikelyForwardingFunction(FT))
        return true;
      auto &SM = D->getASTContext().getSourceManager();
      auto FID = SM.getFileID(SM.getExpansionLoc(D->getLocation()));
      if (!FID.isValid())
        return true;
      return Collector->shouldIndexFile(FID);
    };
  }

  std::unique_ptr<ASTConsumer>
  CreateASTConsumer(CompilerInstance &CI, llvm::StringRef InFile) override {
    PI->record(CI.getPreprocessor());
    CI.getPreprocessor().addPPCallbacks(
        std::make_unique<IncludeGraphCollector>(CI.getSourceManager(), IG));
    HeaderSearchInfo = &CI.getPreprocessor().getHeaderSearchInfo();
    HeaderSearchInfo->getModuleMap().addModuleMapCallbacks(
        std::make_unique<ModuleMapCollector>(CI.getSourceManager(), IG));

    return index::createIndexingASTConsumer(Collector, Opts,
                                            CI.getPreprocessorPtr());
  }

  bool BeginInvocation(CompilerInstance &CI) override {
    // We want all comments, not just the doxygen ones.
    CI.getLangOpts().CommentOpts.ParseAllComments = true;
    CI.getLangOpts().RetainCommentsFromSystemHeaders = true;
    // Index the whole file even if there are warnings and -Werror is set.
    // Avoids some analyses too. Set in two places as we're late to the party.
    CI.getDiagnosticOpts().IgnoreWarnings = true;
    CI.getDiagnostics().setIgnoreAllWarnings(true);
    // Instruct the parser to ask our ASTConsumer if it should skip function
    // bodies. The ASTConsumer will take care of skipping only functions inside
    // the files that we have already processed.
    CI.getFrontendOpts().SkipFunctionBodies = true;
    return true;
  }

  void EndSourceFileAction() override {
    if (HeaderSearchInfo && HeaderSearchInfo->HasIncludeAliasMap())
      for (auto &Node : IG)
        if (Node.getValue().Flags & IncludeGraphNode::SourceFlag::IsTU)
          Node.getValue().Flags |=
              IncludeGraphNode::SourceFlag::HasIncludeAliasState;
    IndexFileIn Result;
    Result.Symbols = Collector->takeSymbols();
    Result.Refs = Collector->takeRefs();
    Result.Relations = Collector->takeRelations();
#ifndef NDEBUG
    // This checks if all nodes are initialized.
    for (const auto &Node : IG)
      assert(Node.getKeyData() == Node.getValue().URI.data());
#endif
    Result.Sources = std::move(IG);
    IndexContentsCallback(std::move(Result));
  }

private:
  std::function<void(IndexFileIn)> IndexContentsCallback;
  std::shared_ptr<SymbolCollector> Collector;
  std::unique_ptr<include_cleaner::PragmaIncludes> PI;
  index::IndexingOptions Opts;
  IncludeGraph IG;
  HeaderSearch *HeaderSearchInfo = nullptr;
};

} // namespace

std::unique_ptr<FrontendAction> createStaticIndexingAction(
    SymbolCollector::Options Opts,
    std::function<void(IndexFileIn)> IndexContentsCallback) {
  index::IndexingOptions IndexOpts;
  IndexOpts.SystemSymbolFilter =
      index::IndexingOptions::SystemSymbolFilterKind::All;
  // We index function-local classes and its member functions only.
  IndexOpts.IndexFunctionLocals = true;
  // We need to delay indexing so instantiations of function bodies become
  // available, this is so we can find constructor calls through `make_unique`.
  IndexOpts.DeferIndexingToEndOfTranslationUnit = true;
  Opts.CollectIncludePath = true;
  if (Opts.Origin == SymbolOrigin::Unknown)
    Opts.Origin = SymbolOrigin::Static;
  Opts.StoreAllDocumentation = false;
  Opts.RefFilter = RefKind::All;
  Opts.RefsInHeaders = true;
  auto PragmaIncludes = std::make_unique<include_cleaner::PragmaIncludes>();
  Opts.PragmaIncludes = PragmaIncludes.get();
  return std::make_unique<IndexAction>(std::make_shared<SymbolCollector>(Opts),
                                       std::move(PragmaIncludes), IndexOpts,
                                       IndexContentsCallback);
}

} // namespace clangd
} // namespace clang
